services:
  - type: web
    name: deported-server
    runtime: node
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 10000
